project:
  type: website

website:
  title: "Sia Chawla"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/siachawla16
format:
  html:
    theme: morph
    css: styles.css



